#################################
#       AAD2_Environment        #
#################################
services:
  aad2_environment:
    image: ${AAD2_IMAGE_NAME}:${AAD2_TAG_NAME}
    container_name: ${AAD2_CONTAINER_NAME}
    volumes:
      - ${LU_WORKING_DIRECTORY}:${INTERNAL_WORKING_DIR}
    command: ${AAD2_COMPOSE_COMMAND}
    networks: 
      aad2-net:

networks:
  aad2-net:
    name: ${AAD2_CONTAINER_NAME}-net
